/* 章節內容：要修改說明文字，只需編輯此檔 */
window.ZEN_SECTIONS=[
{id:"q1",ic:"🎚️",g:"快速上手",t:"影像品質調整",d:"讓多重螢光影像亮度對比更清楚",im:[23],
 st:[["開啟影像後，點左下方 <b>Dimensions</b> 欄位，可切換多重螢光的顯示。"],["用右下方 <b>Display</b> 欄位調整影像品質，點個別色塊可單獨調整一個螢光。",["自動調整：點 Auto（Min/Max &amp; Best Fit）","手動調整：拖曳圖下方三角形，或輸入 Black / White / Gamma"]]],
 nt:[["詳細說明見 <span class=link data-go=\'f5\'>[Display] 欄位說明</span>"]]},
{id:"q2",ic:"📏",g:"快速上手",t:"比例尺繪製",d:"加入比例尺並調整樣式",im:[24,25],
 st:[["開啟影像後，點下方 <b>Graphics</b> 欄位的比例尺選項，影像會出現預設比例尺。"],["調整位置與大小：",["拖曳「數字」＝移動整體","拖曳「數字上方圓形」＝單獨移動文字","拖曳「橫線兩端方形」＝改變比例尺大小"]],["在比例尺上按右鍵 → <b>Format Graphical Element</b> 修改細節（線條形狀/粗細/顏色、文字字形/大小/顏色、相對位置、背景、透明度）。"]],
 nt:[["!必勾：在 Format Graphical Element 中勾選 <b>Zoom with image</b>"]]},
{id:"q3",ic:"🖼️",g:"快速上手",t:"影像圖檔轉出 Image Export",d:"把影像輸出為 jpg / tiff",im:[26],
 st:[["先開啟影像（建議先繪製比例尺、調整影像品質）。"],["左側點 <b>Single</b>。"],["搜尋並點選 <b>Image Export</b>。"],["點擊選擇目標檔案（Input）。"],["設定轉檔格式、儲存位置、檔案名稱。"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["參數細節見 <span class=link data-go=\'p1\'>Image Export 參數設定</span>"]]},
{id:"q4",ic:"🎬",g:"快速上手",t:"影片轉檔製作 Movie Export",d:"把曠時影像輸出成影片",im:[27],
 st:[["開啟影像（先繪製比例尺、調整影像品質）。"],["點選 <b>Single</b>。"],["搜尋並點選 <b>Movie Export</b>。"],["點擊選擇目標檔案。"],["設定格式、影片速度（張數/秒）、儲存位置、檔案名稱。"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["參數細節見 <span class=link data-go=\'p3\'>Movie Export 參數設定</span>"]]},
{id:"q5",ic:"🧩",g:"快速上手",t:"拆解多位點影像 Split Scenes",d:"多位點曠時攝影檔案拆成個別檔案",im:[28],
 st:[["開啟影像（用於多重位點曠時攝影檔案）。"],["點選 <b>Single</b>。"],["搜尋並點選 <b>Splite Scenes (Write files)</b>。"],["點擊選擇目標檔案。"],["設定儲存位置，並勾選保留位點名稱。"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["!必勾「保留個別位置名稱」，否則檔名只會顯示位點順序。"]]},
{id:"f1",ic:"🖥️",g:"欄位介紹",t:"軟體初始介面",d:"認識畫面配置，隱藏用不到的欄位",im:[],
 st:[["<b>調整畫面</b>：初始介面可調整顯示內容，點兩側小箭頭可隱藏無使用欄位；右上角可調整視窗色調與顯示比例。",null,"init-1.jpg"],["<b>認識主要使用欄位</b>：處理（Processing）、主影像、顯示／圖示（Dimensions / Graphics）、影像調整（Display）。",null,"init-2.jpg"]],nt:[]},
{id:"f2",ic:"⚙️",g:"欄位介紹",t:"Processing 處理欄位",d:"選擇轉檔模式與影像",im:["processing.jpg"],
 st:[["<b>Single</b> 單一影像轉檔 / <b>Batch</b> 批次影像轉檔。"],["轉檔模式選擇（Method）。"],["轉檔參數設定（Parameters）。"],["轉檔影像選擇（Input）。"]],nt:[]},
{id:"f3",ic:"🔬",g:"欄位介紹",t:"Dimensions 顯示欄位",d:"縮放、螢光切換、位點與時序",im:[],
 st:[["<b>多重螢光單一影像</b>",["Zoom：影像瀏覽縮放","Tools：影像瀏覽工具（勾選 Navigator 顯示導航視窗）","Channels：點文字＝開/關該波長；點色塊＝切換套色","Single Channel：勾選只顯示單一螢光","Range Indicator：曝光亮度偵測"],"dim-single.jpg"],["<b>多位點與曠時影像</b>（除上述功能外，多出 Time / Scene 兩條軸）",["Time 曠時：拖曳軸點或按播放，瀏覽不同時序影像","Scene 位點：勾選＝顯示單一位點（拖曳/點數字切換）；取消勾選＝同時顯示所有位點","滑鼠停在位置軸會顯示位點名稱"],"dim-multi.jpg"]],nt:[]},
{id:"f4",ic:"✏️",g:"欄位介紹",t:"Graphics 繪圖欄位",d:"框選、文字、比例尺、箭頭、圖形",im:["graphics.jpg"],
 st:[["<b>框選範圍</b>：框選指定範圍。"],["<b>文字</b>：在影像上加入文字標示。"],["<b>比例尺</b>：繪製比例尺（拖曳節點調大小、拖曳中心調位置）。"],["<b>箭頭</b>：加入箭頭標示。"],["<b>圖形框選</b>：矩形、圓形、不規則曲線，自動計算 Area / Diameter / mean Intensity。"],["<b>其他</b>：其他影像細節資訊工具。"]],nt:[]},
{id:"f5",ic:"🌗",g:"欄位介紹",t:"Display 亮度對比調整",d:"自動 / 手動調整、複製參數",im:["display.jpg"],
 st:[["不同螢光顯示：點個別色塊可單獨調整該螢光。"],["<b>自動調整</b>：點選不同模式由系統自動調整。"],["<b>手動調整</b>：拖曳三角圖示或左右邊線，或手動輸入 Black / White / Gamma。"],["設定：選單中 Copy / Paste 可把亮度對比參數複製到其他影像。"]],nt:[]},
{id:"c1",ic:"📄",g:"轉檔步驟",t:"單張照片轉檔 Single",d:"一次處理一個檔案",im:[14,15],
 st:[["<b>選擇模式 Method</b>：用選單點選或直接搜尋，點模式名稱進入下一步。近期使用模式會列在上方。"],["點擊選擇 <b>Input</b> 檔案。"],["調整 <b>Parameter</b> 參數（細節見參數設定）。"],["點選 <b>Apply</b> 進行轉檔。"]],
 nt:[["常用模式：<br>· Export/Import – Image Export：匯出單一/多重螢光影像<br>· Export/Import – Movie Export：製作影片<br>· Utilities – Splite Scenes (Write files)：拆解多位點影像（常用於曠時攝影）"]]},
{id:"c2",ic:"📚",g:"轉檔步驟",t:"批次照片轉檔 Batch",d:"一次處理多個檔案並套用相同參數",im:[16],
 st:[["點選 <b>Batch</b>。"],["新增批次檔案：點 [+Add…] 或直接拖曳檔案進欄位。"],["點其中一個檔案，選擇 Method 並設定 Parameters。"],["設定完成後再點該檔案，按 <b>Copy Parameters</b>。"],["選取其他所有檔案，按 <b>Paste Parameters</b> 套用參數。"],["全選所有檔案，確認儲存路徑：",["預設勾選＝存於原始資料夾","取消勾選並點 […] 可統一更改路徑"]],["點擊 <b>Apply</b> 進行批次轉檔。"]],nt:[]},
{id:"p1",ic:"🖼️",g:"參數設定",t:"Image Export 參數",d:"Export/Import → Image Export",im:[18,19],
 st:[["檔案格式與輸出品質。"],["匯出原始單色影像。"],["匯出套色/調整/標示之影像（勾選匯出單一或多重螢光疊圖）。"],["選擇匯出所有影像或指定部分（點 <b>Define Subset</b>）：",["Channels：點文字開/關螢光（不同組合需重複操作）","Region：Full 原始影像；Rectangle region 框選範圍","Tile：Export selected tiles 匯出原始散裝照片；Crop to selection 將拼圖重新分割（不分割則皆輸入 1）"]],["檔案輸出位置與名稱。"]],
 nt:[["請先勾選右上角 <b>Show All</b>。"]]},
{id:"p2",ic:"🧩",g:"參數設定",t:"Split Scenes 參數",d:"Utilities → Splite Scenes (Write files)",im:[20],
 st:[["更改檔案輸出位置。"],["勾選保留個別位置名稱（必勾）。"]],
 nt:[["請先勾選右上角 <b>Show All</b>。每個位點會拆成獨立 .czi 檔，方便匯出與後製。"]]},
{id:"p3",ic:"🎬",g:"參數設定",t:"Movie Export 參數",d:"Export/Import → Movie Export",im:[21],
 st:[["檔案格式與輸出品質。"],["匯出套色/調整/標示之影像（單一或多重螢光疊圖）。"],["選擇影像呈現比例。"],["設定播放順位與速度（張數/秒）。"],["選擇匯出所有/指定部分（全部/個別螢光/位置/拼圖）。"],["檔案輸出位置與名稱。"]],
 nt:[["請先勾選右上角 <b>Show All</b>。"]]}
];
