/* 章節內容：要修改說明文字，只需編輯此檔 */
window.ZEN_SECTIONS=[
{id:"q1",ic:"🎚️",g:"快速上手",t:"影像品質調整",d:"讓多重螢光影像亮度對比更清楚",im:[],
 st:[["在左下方 <b>Dimensions</b> 欄位的 Channels，點螢光名稱可開／關該螢光的顯示。",null,"iu-1.jpg"],["在右下方 <b>Display</b> 欄位調整亮度對比，點個別螢光色塊可單獨調整。",["自動調整：點 Min/Max 或 Best Fit","手動調整：拖曳下方三角形，或輸入 Black / Gamma / White"],"iu-2.jpg"]],
 nt:[["各項說明見 <span class=link data-go='f5'>Display 亮度對比調整</span>。"]]},
{id:"q2",ic:"📏",g:"快速上手",t:"比例尺繪製",d:"加入比例尺並調整樣式",im:[],
 st:[["點下方 <b>Graphics</b> 欄位的比例尺工具（尺規圖示），影像上會出現預設比例尺。",null,"sc-1.jpg"],["",null,"sc-23.jpg",[["<b>調整位置與大小</b>",["拖曳「數字」＝移動整體","拖曳數字上方圓形＝單獨移動文字","拖曳橫線兩端方形＝改變比例尺大小"]],["在比例尺上按右鍵 → <b>Format Graphical Elements</b>，開啟格式設定。"]]],["<b>修改格式細節</b>",["線條（Line）：顏色、粗細、線條形狀","文字（Text）：字形、大小、顏色、相對位置","背景（Fill）與透明度（Opacity）"],"sc-4.jpg"]],
 nt:[["!必勾：在 Format Graphical Elements 中勾選 <b>Zoom with Image</b>"],["更多繪圖工具見 <span class=link data-go='f4'>Graphics 繪圖欄位</span>。"]]},
{id:"q3",ic:"🖼️",g:"快速上手",t:"影像圖檔轉出 Image Export",d:"把影像輸出為 jpg / tiff",im:[],pre:[["請先開啟影像，建議先完成比例尺繪製與影像品質調整。"]],
 st:[["",null,"im-12.jpg",[["在左側 Processing 欄位點選 <b>Single</b>。"],["在 Method 的 Search 欄輸入關鍵字（如 ima），點選 <b>Image Export</b>。"]]],["點擊 <b>Input</b> 區域，選擇要處理的檔案。",null,"im-3.jpg"],["設定轉檔格式（Filetype）、儲存位置（Export To）、檔案名稱（Prefix）。",null,"im-4.jpg"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["參數細節見 <span class=link data-go='p1'>Image Export 參數設定</span>。"]]},
{id:"q4",ic:"🎬",g:"快速上手",t:"影片轉檔製作 Movie Export",d:"把曠時影像輸出成影片",im:[],pre:[["請先開啟影像，建議先完成比例尺繪製與影像品質調整。"]],
 st:[["",null,"mo-12.jpg",[["在左側 Processing 欄位點選 <b>Single</b>。"],["在 Method 的 Search 欄輸入關鍵字（如 mo），點選 <b>Movie Export</b>。"]]],["點擊 <b>Input</b> 區域，選擇要處理的檔案。",null,"mo-3.jpg"],["設定影片格式（Format）、影片速度（Mapping，張數/秒）、儲存位置（Export To）、檔案名稱（Prefix）。",null,"mo-4.jpg"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["參數細節見 <span class=link data-go='p3'>Movie Export 參數設定</span>。"]]},
{id:"q5",ic:"🧩",g:"快速上手",t:"拆解多位點影像 Split Scenes",d:"多位點曠時攝影檔案拆成個別檔案",im:[],pre:[["請先開啟多位點曠時攝影檔案。"]],
 st:[["",null,"sp-12.jpg",[["在左側 Processing 欄位點選 <b>Single</b>。"],["在 Method 的 Search 欄輸入關鍵字（如 sp），點選 <b>Split Scenes (Write files)</b>（注意不是上方的 Split Scenes）。"]]],["點擊 <b>Input</b> 區域，選擇要處理的檔案。",null,"sp-3.jpg"],["設定儲存位置（Output Folder），並確認勾選 <b>Include Scene Information in Generated File Name</b>。",null,"sp-4.jpg"],["點擊 <b>Apply</b> 開始轉檔。"]],
 nt:[["!必勾「Include Scene Information…」，否則檔名只會顯示位點順序。"],["參數細節見 <span class=link data-go='p2'>Split Scenes 參數設定</span>。"]]},
{id:"f1",ic:"🖥️",g:"欄位介紹",t:"軟體初始介面",d:"認識畫面配置，隱藏用不到的欄位",im:[],
 st:[["<b>調整畫面</b>：初始介面可調整顯示內容，點兩側小箭頭可隱藏無使用欄位；右上角可調整視窗色調與顯示比例。",null,"init-1.jpg"],["<b>認識主要使用欄位</b>：處理（Processing）、主影像、顯示／圖示（Dimensions / Graphics）、影像調整（Display）。",null,"init-2.jpg"]],nt:[]},
{id:"f2",ic:"⚙️",g:"欄位介紹",t:"Processing 處理欄位",d:"選擇轉檔模式與影像",im:["processing.jpg"],
 st:[["<b>Single</b> 單一影像轉檔 / <b>Batch</b> 批次影像轉檔。"],["轉檔模式選擇（Method）。"],["轉檔參數設定（Parameters）。"],["轉檔影像選擇（Input）。"]],nt:[]},
{id:"f3",ic:"🔬",g:"欄位介紹",t:"Dimensions 顯示欄位",d:"縮放、螢光切換、位點與時序",im:[],
 st:[["<b>多重螢光單一影像</b>",["Zoom：影像瀏覽縮放","Tools：影像瀏覽工具（勾選 Navigator 顯示導航視窗）","Channels：點文字＝開/關該波長；點色塊＝切換套色","Single Channel：勾選只顯示單一螢光","Range Indicator：曝光亮度偵測"],"dim-single.jpg"],["<b>多位點與曠時影像</b>（除上述功能外，多出 Time / Scene 兩條軸）",["Time 曠時：拖曳軸點或按播放，瀏覽不同時序影像","Scene 位點：勾選＝顯示單一位點（拖曳/點數字切換）；取消勾選＝同時顯示所有位點","滑鼠停在位置軸會顯示位點名稱"],"dim-multi.jpg"]],nt:[]},
{id:"f4",ic:"✏️",g:"欄位介紹",t:"Graphics 繪圖欄位",d:"框選、文字、比例尺、箭頭、圖形",im:["graphics.jpg"],
 st:[["<b>框選範圍</b>：框選指定範圍。"],["<b>文字</b>：在影像上加入文字標示。"],["<b>比例尺</b>：繪製比例尺（拖曳節點調大小、拖曳中心調位置）。"],["<b>箭頭</b>：加入箭頭標示。"],["<b>圖形框選</b>：矩形、圓形、不規則曲線，自動計算 Area / Diameter / mean Intensity。"],["<b>其他</b>：其他影像細節資訊工具。"]],nt:[]},
{id:"f5",ic:"🌗",g:"欄位介紹",t:"Display 亮度對比調整",d:"自動 / 手動調整、複製參數",im:["display.jpg"],
 st:[["不同螢光顯示：點個別色塊可單獨調整該螢光。"],["<b>自動調整</b>：點選不同模式由系統自動調整。"],["<b>手動調整</b>：拖曳三角圖示或左右邊線，或手動輸入 Black / White / Gamma。"],["設定：選單中 Copy / Paste 可把亮度對比參數複製到其他影像。"]],nt:[]},
{id:"c1",ic:"📄",g:"轉檔步驟",t:"單張照片轉檔 Single",d:"一次處理一個檔案",im:[],
 st:[["在左側 Processing 欄位點選 <b>Single</b>。",null,"single-0.jpg"],["<b>選擇模式（Method）</b>：展開 Method，用以下任一方式選擇轉檔模式。",["近期使用模式：最近用過的模式會列在最上方，直接點選","直接輸入搜尋：在 Search 欄輸入模式名稱","點擊選單選擇：展開分類（如 Export/Import）後點選模式"],"single-1-method.jpg"],["<b>選擇影像（Input）</b>：點擊 Input 區域，從跳出的清單中點選要轉檔的檔案。",["清單會顯示檔名、檔案大小與縮圖"],"single-2-input.jpg"],["<b>設定參數（Parameters）</b>：依所選模式調整參數（右圖以 Image Export 為例）。",["Filetype：輸出檔案格式","Quality：輸出品質","Resize：影像縮放比例","Export To：輸出位置（點 … 選擇資料夾）","Prefix：檔名前綴","Defaults：還原為預設值"],"single-3-parameter.jpg"],["<b>開始轉檔（Apply）</b>：確認上方 Function 顯示的是所選模式，點擊 <b>Apply</b> 開始轉檔。",null,"single-4-apply.jpg"]],
 nt:[["!若看不到完整參數，請先勾選 Parameters 右側的 <b>Show All</b>。"],["各模式的參數不同，細節見 <span class=link data-go='p1'>Image Export 參數設定</span>、<span class=link data-go='p3'>Movie Export 參數設定</span>。"],["常用模式：<br>· Export/Import → Image Export：匯出單一/多重螢光影像<br>· Export/Import → Movie Export：製作影片<br>· Utilities → Split Scenes (Write files)：拆解多位點影像（常用於曠時攝影）"]]},
{id:"c2",ic:"📚",g:"轉檔步驟",t:"批次照片轉檔 Batch",d:"一次處理多個檔案並套用相同參數",im:[],
 st:[["",null,"bt-12.jpg",[["在 Processing 欄位點選 <b>Batch</b>。"],["在 Batch Method 清單選擇轉檔模式（如 <b>Image Export</b>）。"]]],["<b>加入檔案並選取其中一個</b>",["點 <b>+ Add…</b> 加入要轉檔的檔案，或直接拖曳檔案進清單（可一次加入多個）","點選清單中的其中一個檔案作為範本，下方會顯示它的 Method 與 Parameters 欄位"],["~~bt-add.jpg","~~bt-sel.jpg","~bt-mp.jpg"]],["<b>設定 Parameters</b>：依所選模式調整參數（右圖以 Image Export 為例）。",null,"bt-4.jpg"],["",null,"~~bt-56.jpg",[["參數設定完成後，再點選該檔案，按 <b>Copy Parameters</b>。"],["選取其他所有檔案，按 <b>Paste Parameters</b> 套用相同參數。"]]],["<b>設定儲存路徑</b>：全選所有檔案，確認儲存位置。",["勾選 Use Input Folder as Output Folder：存回各檔案所在的原始資料夾","取消勾選並點 … ：統一指定新的儲存路徑"],"~~bt-7.jpg"],["<b>開始轉檔</b>：確認為 Batch 模式後，點擊 <b>Apply</b>。",null,"bt-8.jpg"]],
 nt:[["!若看不到完整參數，請先勾選 Parameters 右側的 <b>Show All</b>。"],["各模式的參數細節見 <span class=link data-go='p1'>Image Export 參數設定</span>、<span class=link data-go='p3'>Movie Export 參數設定</span>。"]]},
{id:"p1",ic:"🖼️",g:"參數設定",t:"Image Export 參數",d:"Export/Import → Image Export（圖中編號對應步驟編號）",im:["ie-main.jpg"],
 st:[["<b>檔案格式與品質</b>",["Filetype：輸出檔案格式（如 JPEG、TIFF）","Quality：輸出品質","Resize：影像縮放比例"]],["<b>Original data</b>：匯出原始單色影像（未套色、未調整）。"],["<b>Apply display curve and channel color</b>：匯出套色、調整亮度對比、含標示的影像。",["Burn in graphics：將比例尺等標示一併嵌入影像（Zoom 可設定縮放）","Merged channels image：匯出多重螢光疊圖","Individual channel images：匯出各螢光單張影像","Use channel names：檔名使用螢光通道名稱"]],["<b>選擇匯出範圍</b>",["Use full set of dimensions：匯出全部影像","Define subset：只匯出指定部分，選擇後會展開下方選項","Channels：點文字開/關螢光（不同組合需重複操作）","Region：Full＝原始影像；Rectangle region＝框選範圍","Tiles：Export selected tiles＝匯出原始散裝照片；Crop to selection and generate new tiles＝將拼圖重新分割（不分割則 Columns、Rows 皆輸入 1）"],"~ie-subset.jpg"],["<b>輸出位置與檔名</b>",["Export To：輸出資料夾（點 … 選擇）","Create folder：自動建立資料夾存放","Prefix：檔名前綴","Defaults：還原為預設值"]]],
 nt:[["!請先勾選右上角 <b>Show All</b>，才會看到完整參數。"]]},
{id:"p3",ic:"🎬",g:"參數設定",t:"Movie Export 參數",d:"Export/Import → Movie Export（圖中編號對應步驟編號）",im:["mv-main.jpg"],
 st:[["<b>檔案格式與品質</b>",["Format：影片格式（如 AVI）","Size/Rate：影片尺寸與播放速率","Quality：輸出品質"]],["<b>匯出套色、調整、標示的影像</b>",["Burn in graphics：將比例尺等標示一併嵌入影片（Zoom 可設定縮放）","Merged channels image：多重螢光疊圖","Individual channel images：各螢光單張影像"]],["<b>Fitting</b>：選擇影像呈現比例。"],["<b>播放順位與速度</b>",["Sequence：Time Series＝依時間順序；Channels＝依螢光順序","Mapping：設定每張影像的播放幀數與速度（張數/秒）","Image count 顯示影像張數；Final movie length 顯示預估影片長度"]],["<b>選擇匯出範圍</b>",["Use full set of dimensions：匯出全部影像","Define subset：只匯出指定部分，選擇後會展開下方選項","Channels：選擇要匯出的螢光","Time：選擇時間點（如 Extract Single＝單一時間點）","Region：Full＝完整範圍"],"~mv-subset.jpg"],["<b>輸出位置與檔名</b>",["Export To：輸出資料夾（點 … 選擇）","Prefix：檔名前綴"]]],
 nt:[["!請先勾選右上角 <b>Show All</b>，才會看到完整參數。"]]},
{id:"p2",ic:"🧩",g:"參數設定",t:"Split Scenes 參數",d:"Utilities → Split Scenes (Write files)",im:["split.jpg"],
 st:[["<b>Output Folder</b>：更改檔案輸出位置（點 … 選擇資料夾）。"],["<b>Include Scene Information in Generated File Name</b>：勾選，檔名才會保留個別位點名稱。"]],
 nt:[["!第 2 步必勾，否則檔名只會顯示位點順序。","請先勾選右上角 <b>Show All</b>。每個位點會拆成獨立 .czi 檔，方便匯出與後製。","Overwrite existing files 為覆蓋同名檔案選項，一般維持不勾選。"]]}
];
